:labname: Environment Setup

include::../include/00_0_Lab_Header.adoc[]

== {labname} Lab

:numbered:

== Introduction to Environment Setup

This course provides you with hands-on experience working with some of the features of Red Hat^(R)^ Integration Y22Q1 release.

For this course, you deploy a single-node OpenShift Container Platform cluster, which is an OpenShift control plane and worker node all in one large virtual machine (VM).

Here is an example of the output of an `oc get nodes` command that shows that one node is both a `master` and a `worker`:

.Sample Output
----
NAME                                         STATUS   ROLES           AGE   VERSION
ip-10-0-143-248.us-east-2.compute.internal   Ready    master,worker   92m   v1.22.3+ffbb954
----

The environment automatically shuts down after approximately four hours of runtime, so try to finish this course in one sitting.
Please also use this environment for your own experiments with Red Hat Integration.

Refer back to the these directions if you are unable to complete these labs within four hours or if you need to restart or redeploy the environment.

== Provision Lab Environment

In this section, you provision the lab environment to provide access to all of the components required to perform the labs.
The lab environment is a cloud-based environment, so that you can access it over the Internet from anywhere.
The Red Hat team has made efforts to provide a lab environment that is sufficiently powered to meet the needs of your labs.
Feel free to experiment with this cluster.

In the labs for this course, you use the OpenShift Container Platform web console and a Student Environment for most of the tasks.

=== Deploy Openshift Container Platform

In this section, you deploy the single-node OpenShift Container Platform environment for this course.

.Procedure
. Go to the {opentlc_portal} and use your OPENTLC credentials to log in.
. Navigate to *Services -> Catalogs -> All Services -> {opentlc_catalog_name}*.
. On the left, select *{opentlc_catalog_item_name1}*.
. On the right, click *Order*.
. On the bottom right, click *Submit*.
+
[IMPORTANT]
Do not select *App Control -> Start* after ordering the environment.
Selecting *Start* may corrupt the lab environment or cause other complications.

* After a few minutes, expect to receive an email with instructions on how to connect to the environment.

. Read the email carefully and specifically note the following:
* The URL for the OpenShift Container Platform web console and the necessary credentials.
* The host name for your bastion environment and instructions for connecting to it via SSH.

=== Start Openshift Environment After Shutdown

To conserve resources, the lab environment shuts down automatically after four hours.
This section provides the steps to restart the environment for this course after it has shut down.

.Procedure
. Go to the {opentlc_portal} and use your OPENTLC credentials to log in.
. Navigate to *Services -> My Services* (this should be the screen shown right after logging in).
. In the list of your services, select your lab environment.
. Navigate to *App Control -> Start* to start your lab environment.
. Select *Yes* at the *Are you sure?* prompt.
. On the bottom right, click *Submit*.

After a few minutes, expect to receive an email letting you know that the Hands-On with OpenShift 4.9 environment has started.

=== Deploy Student Environment

In the labs for this course, you use the command line for most of the tasks. The labs assume that you are using the provided student environment.

In this section, you deploy the student environment for this course.

. Go to the {opentlc_portal} and use your OPENTLC credentials to log in.
. Navigate to *Services -> Catalogs -> All Services -> {opentlc_catalog_name}*.
. On the left, select *{opentlc_student_catalog_item_name1}*.
. On the right, click *Order*.
. On the bottom right, click *Submit*.
+
[IMPORTANT]
Do not select *App Control -> Start* after ordering the student environment. This is not necessary in this environment. Selecting *Start* may corrupt the lab environment or cause other complications.

* After a few minutes, expect to receive an email message with instructions on how to connect to the environment.

. Read the message carefully and specifically note the following, which are included in the message:
* A hostname for your student environment
* A username and password for your student environment
* A command to connect to the student environment

=== Start Student Environment After Shut Down

To conserve resources, the student environment shuts down automatically after eight hours.
In this section, you restart the student environment for this course after it automatically shuts down.

[IMPORTANT]
====
Perform this section only if the environment shut down.
====

. Go to the {opentlc_portal} and use your OPENTLC credentials to log in.
. Navigate to *Services -> My Services* (the screen shown directly after logging in).
. In the list of services, select your student environment.
. Select *App Control -> Start* to start your student environment.
. At the *Are you sure?* prompt, select *Yes*.
. On the bottom right, click *Submit*.

After a few minutes, expect to receive an email message letting you know that the student environment started.

=== Test Server Connections

The student environment serves as an access point into the environment and is not part of Red Hat^(R)^ OpenShift^(R)^ Container Platform's environment.

. Connect to your student environment by using the command and password sent to you via email.
+
.Sample Command
[source,sh]
----
ssh lab-user@studentvm.<GUID>.<some_base_domain>
----
+
. Verify that the `$GUID` variable is set correctly for your environment.
+
[source,sh]
----
echo $GUID
----
+
.Sample Output
[source,texinfo]
----
c3po
----
* The GUID may be a four- or five-letter alphanumeric string.

=== Connect to OpenShift Cluster

After you are connected to your student environment, you can log in to the OpenShift cluster using your admin credentials.

=== Save OpenShift Configuration to Variables

To make the following labs easier, you save a few OpenShift settings to environment variables in your student VM.

[TIP]
====
You can find the values for _all_ of these variables in the class Miro board.
====

. Set up an environment variable with your `OpenShift Cluster apps` domain.
+
[source,sh]
----
# Set your OpenShift Cluster apps domain here
# Replace XXXX with the GUID and YYYY with the sandbox number
export OCP_APPS_DOMAIN=apps.cluster-XXXX.XXXX.sandboxYYYY.opentlc.com

# Save to .bashrc for future sessions
ansible localhost -m lineinfile -a "path=${HOME}/.bashrc regexp='^export OCP_APPS_DOMAIN' line='export OCP_APPS_DOMAIN=${OCP_APPS_DOMAIN}'"
----

. Save your assigned OpenShift username, password and API endpoint to an environment variable for easier reuse.
+
[source,sh]
----
# Use your cluster admin username from your provisioning email
export OCP_USER=admin

# Use your cluster admin password from your provisioning email
export OCP_PASSWORD=r3dh4t1!

# Use the Cluster API URL from your provisioning email
export OCP_API=https://api.cluster-XXXX.XXXX.sandboxYYYY.opentlc.com:6443

# Save to .bashrc for future sessions
ansible localhost -m lineinfile -a "path=$HOME/.bashrc regexp='^export OCP_USER' line='export OCP_USER=${OCP_USER}'"

ansible localhost -m lineinfile -a "path=$HOME/.bashrc regexp='^export OCP_PASSWORD' line='export OCP_PASSWORD=${OCP_PASSWORD}'"

ansible localhost -m lineinfile -a "path=$HOME/.bashrc regexp='^export OCP_API' line='export OCP_API=${OCP_API}'"
----

. Use the `oc login` command to log in to the cluster.
+
[source,sh]
----
oc login --insecure-skip-tls-verify=true -u ${OCP_USER} -p ${OCP_PASSWORD} ${OCP_API}
----
+
.Sample Output
[source,texinfo]
----
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
----

== Complete Environment Overview

You are using a shared cluster for this course. Your instructor already configured the shared cluster with the  services required for this course.

== Install Additional Plug-ins into Lab Environment

Your lab environment is a VM that is provisioned in the cloud. There are several packages already installed in this VM:

* OpenJDK 11
* Maven: A Java(TM) build tool
* Mandrel: A high-speed Java VM with the capability to compile Java Quarkus applications into native code
* `kubeseal`: A command line tool to manage sealed secrets
* Several OpenShift command line utilities
** `oc`: OpenShift CLI
** `kn`: OpenShift Serverless CLI
** `podman`: For managing container images and containers
** `ansible`: For some simple admin tasks

You will also require the Camel K CLI.

. Install `kamel` by copying and pasting the entire code snippet below, including the brackets.
+
[source,sh]
----
(
  rm -rf ~/kamelk;
  mkdir ~/kamelk;
  cd ~/kamelk &&
  curl -fsSLO "https://downloads.apache.org/camel/camel-k/1.9.2/camel-k-client-1.9.2-linux-64bit.tar.gz" &&
  tar zxvf "camel-k-client-1.9.2-linux-64bit.tar.gz"
)
----

. Set up the path for your environment to include the location of the CLI.
+
[source,sh]
----
ansible localhost -m lineinfile -a "path=${HOME}/.bashrc line='export PATH=\"${HOME}/kamelk:$PATH\"'"

source ${HOME}/.bashrc
----

== Summary

Your Hands-On with Integration Y22Q1 environment is ready to use.

Proceed to the next module to get started.
