:labname: Environment Setup

include::../include/00_0_Lab_Header.adoc[]

== {labname} Lab

:numbered:

== Introduction to Environment Setup

This course provides you with hands-on experience working with some of the features of Red Hat^(R)^ Integration Y22Q1 release.

For this course, you deploy a single-node OpenShift Container Platform cluster, which is an OpenShift control plane and worker node all in one large virtual machine (VM).

Here is an example of the output of an `oc get nodes` command that shows that one node is both a `master` and a `worker`:

.Sample Output
----
NAME                                         STATUS   ROLES           AGE   VERSION
ip-10-0-143-248.us-east-2.compute.internal   Ready    master,worker   92m   v1.22.3+ffbb954
----

The environment automatically shuts down after approximately four hours of runtime, so try to finish this course in one sitting.
Please also use this environment for your own experiments with Red Hat Integration.

Refer back to the these directions if you are unable to complete these labs within four hours or if you need to restart or redeploy the environment.

== Provision Lab Environment

In this section, you provision the lab environment to provide access to all of the components required to perform the labs.
The lab environment is a cloud-based environment, so that you can access it over the Internet from anywhere.
The Red Hat team has made efforts to provide a lab environment that is sufficiently powered to meet the needs of your labs.
Feel free to experiment with this cluster.

In the labs for this course, you use the OpenShift Container Platform web console and the command line for most of the tasks.

=== Deploy Environment

In this section, you deploy the single-node OpenShift Container Platform environment for this course.

.Procedure
. Go to the {opentlc_portal} and use your OPENTLC credentials to log in.
. Navigate to *Services -> Catalogs -> All Services -> {opentlc_catalog_name}*.
. On the left, select *{opentlc_catalog_item_name1}*.
. On the right, click *Order*.
. On the bottom right, click *Submit*.
+
[IMPORTANT]
Do not select *App Control -> Start* after ordering the environment.
Selecting *Start* may corrupt the lab environment or cause other complications.

* After a few minutes, expect to receive an email with instructions on how to connect to the environment.

. Read the email carefully and specifically note the following:
* The URL for the OpenShift Container Platform web console and the necessary credentials.
* The host name for your bastion environment and instructions for connecting to it via SSH.

== Start Environment After Shutdown

To conserve resources, the lab environment shuts down automatically after four hours.
This section provides the steps to restart the environment for this course after it has shut down.

.Procedure
. Go to the {opentlc_portal} and use your OPENTLC credentials to log in.
. Navigate to *Services -> My Services* (this should be the screen shown right after logging in).
. In the list of your services, select your lab environment.
. Navigate to *App Control -> Start* to start your lab environment.
. Select *Yes* at the *Are you sure?* prompt.
. On the bottom right, click *Submit*.

After a few minutes, expect to receive an email letting you know that the Hands-On with OpenShift 4.9 environment has started.

== Test Access to OpenShift Container Platform
Now that you have provisioned the environment, you need to verify that you can access the lab's connections.

=== Test Web Console Connections
First make sure you can access the OpenShift Container Platform web console.

.Procedure
. In the provisioning email you received, click the URL for the OpenShift Container Platform web console.
. Log in with the credentials provided in the email.

=== Test Server Connections

The bastion host serves as an important access point into the environment, so you need to make sure you can connect to it.

.Procedure
. Connect to your bastion host using the command and password you received in the provisioning email:
+
.Sample Command
[source,bash]
----
ssh lab-user@bastion.<$GUID>.<$BASEDOMAIN>
----
+
. Verify that the GUID variable is set correctly for your environment:
+
[source,bash]
----
echo $GUID
----
+
.Sample Output
----
c3po
----
+
[NOTE]
Your GUID may be a 4- or 5-character alphanumeric string.

=== Connect to OpenShift Container Platform Cluster

Once you are connected to your lab environment, you can log in to the OpenShift Container Platform cluster.

* In the provisioning email you received, note the following:
** The OpenShift credentials for two OpenShift users: `admin` user and `user1` unprivileged user.
** The URL for the API of the cluster--for example, {ocp_api}
** The URL for the web console of the cluster--for example, {ocp_console}

.Procedure
. Use the `oc login` command to log in to the cluster:
+
[source,bash]
----
oc login -u <username> -p <password from email> <OpenShift API URL from email>
----
+
.Sample Output
----
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
----

== Set Up Local Environment

This lab requires several command line interfaces.  Navigate to your Openshift console and select *Help -> Command line tools*.  Download the CLI's appropriate for your operating system if you do not have them on your client machine:

* oc - OpenShift Command Line Interface (CLI)
* kamel - Red Hat Integration - Camel K - Command Line Interface
* kn - OpenShift Serverless Command Line Interface (CLI)

You will be required to run Maven commands.  The Maven installation instructions are availabe at https://maven.apache.org/install.html

You will require the git CLI to interact with source code repositories.  The Git installation instructions are available at https://github.com/git-guides/install-git.

You will also require JDK 11 or greater.  The OpenJDK installation instructions are available at https://openjdk.java.net/install/.



== Summary


Congratulations, your Hands-On Integration Y22Q1 environment is ready to use.
